trigger:
- refs/heads/*
- refs/pull/*/merge
- refs/tags/*

jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
      x86:
        TARGET_CPU: x86
  steps:
  - template: building/azure-pipelines-template.yml

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
  steps:
  - template: building/azure-pipelines-template.yml

- job: linux_build
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
      x86:
        TARGET_CPU: x86
      arm:
        TARGET_CPU: arm
      arm64:
        TARGET_CPU: arm64
  steps:
  - script: |
      sudo apt update
      sudo apt install -y software-properties-common
      sudo add-apt-repository -y ppa:webkit-team/ppa
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt update
      sudo apt install -y git cmake xvfb g++-6 libgtk-3-dev libnotify-dev webkit2gtk-4.0-dev
    displayName: Install dependencies
  - script: |
      sudo apt install -y gcc-6-multilib g++-6-multilib
    displayName: Install cross-compile toolchains
    condition: ne(variables['TARGET_CPU'], 'x64')
  - script: |
      sudo apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross linux-libc-dev-armhf-cross binutils-aarch64-linux-gnu
    displayName: Install ARM toolchains
    condition: startsWith(variables['TARGET_CPU'], 'arm')
  - template: building/azure-pipelines-template.yml
