trigger:
- refs/heads/*
- refs/pull/*/merge
- refs/tags/*

jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
      x86:
        TARGET_CPU: x86

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
  steps:
  - template: azure-pipelines-template.yml

- job: linux_build
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      x64:
        TARGET_CPU: x64
      x86:
        TARGET_CPU: x86
      arm:
        TARGET_CPU: arm
      arm64:
        TARGET_CPU: arm64
