trigger:
- refs/heads/*
- refs/pull/*/merge
- refs/tags/*

jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
      x86:
        TARGET_ARCH: x86
  timeoutInMinutes: 120
  cancelTimeoutInMinutes: 120

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64

- job: linux_build
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
      x86:
        TARGET_ARCH: x86
      arm:
        TARGET_ARCH: arm
      arm64:
        TARGET_ARCH: arm64